### ISSUE TITLE
the code of paper`https://omegafragger.github.io/publication/pacl_cvpr_2023/`

### ISSUE THREAD

**Issue by jinx2018** [omegafragger/DDU#7]
Hi! when will you release the code of paper `Open Vocabulary Semantic Segmentation with Patch Aligned Contrastive Learning` cvpr2023 ?

**Comment by omegafragger** [comment]
Hi! Thanks for reaching out. We are working on the code and training models and this will take some time. Unfortunately, we can't give a timeline for this but I'd suggest sending me an email on jishnu.mukhoti@eng.ox.ac.uk if you have questions about PACL in the mean time.

I'll close this issue since this is not related to DDU.
